# Generated by Django 2.0.5 on 2018-07-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_auto_20180707_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
