# Generated by Django 2.0.5 on 2018-08-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_auto_20180811_0208'),
        ('monitoring', '0016_auto_20180810_1857'),
    ]

    operations = [
    ]
