# Generated by Django 2.0.5 on 2018-11-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical_price_reference',
            name='chemical',
            field=models.TextField(default=''),
        ),
    ]
