# Generated by Django 2.0.5 on 2018-07-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20180703_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='type',
        ),
        migrations.RemoveField(
            model_name='type',
            name='user',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
