# Generated by Django 2.0.5 on 2018-11-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20181101_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical_item',
            name='chemicalUsageLimit',
        ),
        migrations.AddField(
            model_name='chemical_price_reference',
            name='quantity',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='date',
            field=models.DateField(default='2018-11-02', null=True),
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='mobileNumber',
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='notification_table',
            name='date',
            field=models.DateField(default='2018-11-02', null=True),
        ),
    ]
