# Generated by Django 2.0.5 on 2018-11-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20181103_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipaddress_ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='date',
            field=models.DateField(default='2018-11-09', null=True),
        ),
        migrations.AlterField(
            model_name='notification_table',
            name='date',
            field=models.DateField(default='2018-11-09', null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='pool_ip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoring.ipaddress_ref'),
        ),
    ]
