# Generated by Django 2.0.5 on 2018-11-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20181102_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical_price_reference',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8),
        ),
    ]
