# Generated by Django 2.0.5 on 2018-11-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20181109_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='date',
            field=models.DateField(default='2018-11-10', null=True),
        ),
        migrations.AlterField(
            model_name='notification_table',
            name='date',
            field=models.DateField(default='2018-11-10', null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_ip',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoring.ipaddress_ref'),
        ),
    ]
