# Generated by Django 2.0.5 on 2018-07-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_chlorine_effectiveness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceschedule',
            old_name='timeEnd',
            new_name='estimatedEnd',
        ),
        migrations.RenameField(
            model_name='maintenanceschedule',
            old_name='timeStart',
            new_name='estimatedStart',
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='scheduledEnd',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='scheduledStart',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='status',
            field=models.TextField(default='Notified'),
        ),
    ]
