# Generated by Django 2.0.5 on 2018-07-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_auto_20180714_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Usertype_Ref'),
        ),
    ]
