# Generated by Django 2.0.5 on 2018-07-13 21:04
from __future__ import unicode_literals

from django.db import migrations, models
from decimal import Decimal
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_auto_20180714_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='act_bakingsoda',
            field=models.DecimalField(decimal_places=2, default=Decimal(0), max_digits=8),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='est_bakingsoda',
            field=models.DecimalField(decimal_places=2, default=Decimal(0), max_digits=8),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Usertype_Ref'),
        ),
    ]
