# Generated by Django 2.0.5 on 2018-08-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_auto_20180808_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_table',
            name='date',
            field=models.DateField(default='2018-08-11', null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='date',
            field=models.DateField(default='2018-08-11', null=True),
        ),
    ]
