# Generated by Django 2.0.5 on 2018-08-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_auto_20180811_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_table',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notification_table',
            name='type',
            field=models.TextField(default='Pool Technician'),
        ),
    ]
