# Generated by Django 2.0.5 on 2018-10-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_auto_20180811_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='date',
            field=models.DateField(default='2018-10-12', null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='status',
            field=models.TextField(default='Scheduled'),
        ),
        migrations.AlterField(
            model_name='notification_table',
            name='date',
            field=models.DateField(default='2018-10-12', null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Usertype_Ref'),
        ),
    ]
