# Generated by Django 2.0.5 on 2018-10-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_auto_20181014_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='date',
            field=models.DateField(default='2018-10-15', null=True),
        ),
        migrations.AlterField(
            model_name='notification_table',
            name='date',
            field=models.DateField(default='2018-10-15', null=True),
        ),
    ]
