# Generated by Django 2.0.5 on 2018-10-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_auto_20181015_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='pool_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_location',
            field=models.CharField(default='', max_length=250),
        ),
    ]
