# Generated by Django 2.0.5 on 2018-10-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0023_auto_20181015_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upool',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Pool'),
        ),
    ]
