# Generated by Django 2.0.5 on 2018-10-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_auto_20181015_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upool',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='upool',
            name='user',
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='date',
            field=models.DateField(default='2018-10-17', null=True),
        ),
        migrations.AlterField(
            model_name='notification_table',
            name='date',
            field=models.DateField(default='2018-10-17', null=True),
        ),
        migrations.DeleteModel(
            name='uPool',
        ),
    ]
