# Generated by Django 2.0.5 on 2018-10-17 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0026_upool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool_Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Pool')),
            ],
        ),
        migrations.AlterField(
            model_name='upool',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Pool_Ref'),
        ),
    ]
