# Generated by Django 2.0.5 on 2018-10-17 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0029_auto_20181017_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upool',
            name='pool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Pool_Ref'),
        ),
    ]
