# Generated by Django 2.0.5 on 2018-10-17 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0030_auto_20181017_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool_ref',
            name='pool',
        ),
        migrations.AddField(
            model_name='pool_ref',
            name='pool_ref',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='upool',
            name='pool',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='monitoring.Pool_Ref'),
        ),
    ]
