# Generated by Django 2.0.5 on 2018-10-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0031_auto_20181017_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upool',
            name='pool',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='monitoring.Pool'),
        ),
        migrations.DeleteModel(
            name='Pool_Ref',
        ),
    ]
