# Generated by Django 2.0.5 on 2018-10-17 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0033_auto_20181017_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool_Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Pool')),
            ],
        ),
        migrations.CreateModel(
            name='uPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Pool')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
