# Generated by Django 2.0.5 on 2018-10-17 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0034_pool_ref_upool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upool',
            name='pool',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Pool_Ref'),
        ),
    ]
