# Generated by Django 2.0.5 on 2018-10-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0035_auto_20181017_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool_ref',
            name='pool',
        ),
        migrations.AlterField(
            model_name='upool',
            name='pool',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Pool'),
        ),
        migrations.DeleteModel(
            name='Pool_Ref',
        ),
    ]
